-- Script generated by Redgate Compare v1.15.1.10347
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.games_game_id_seq...';END$$;
CREATE SEQUENCE public.games_game_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.games...';END$$;
CREATE TABLE public.games (
    game_id integer NOT NULL DEFAULT nextval('public.games_game_id_seq'::regclass),
    date date,
    home_team_id integer,
    away_team_id integer,
    home_team_score integer,
    away_team_score integer
);
ALTER TABLE public.games ADD CONSTRAINT games_pkey PRIMARY KEY (game_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.games_game_id_seq...';END$$;
ALTER SEQUENCE public.games_game_id_seq OWNED BY public.games.game_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.players_player_id_seq...';END$$;
CREATE SEQUENCE public.players_player_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.players...';END$$;
CREATE TABLE public.players (
    player_id integer NOT NULL DEFAULT nextval('public.players_player_id_seq'::regclass),
    name character varying(50),
    "position" character varying(20),
    team_id integer
);
ALTER TABLE public.players ADD CONSTRAINT players_pkey PRIMARY KEY (player_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.players_player_id_seq...';END$$;
ALTER SEQUENCE public.players_player_id_seq OWNED BY public.players.player_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.teams_team_id_seq...';END$$;
CREATE SEQUENCE public.teams_team_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.teams...';END$$;
CREATE TABLE public.teams (
    team_id integer NOT NULL DEFAULT nextval('public.teams_team_id_seq'::regclass),
    name character varying(50),
    city character varying(50),
    founded_year integer
);
ALTER TABLE public.teams ADD CONSTRAINT teams_pkey PRIMARY KEY (team_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.teams_team_id_seq...';END$$;
ALTER SEQUENCE public.teams_team_id_seq OWNED BY public.teams.team_id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.games.games_away_team_id_fkey...';END$$;
ALTER TABLE public.games ADD CONSTRAINT games_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams (team_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.games.games_home_team_id_fkey...';END$$;
ALTER TABLE public.games ADD CONSTRAINT games_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams (team_id);


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.players.players_team_id_fkey...';END$$;
ALTER TABLE public.players ADD CONSTRAINT players_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams (team_id);

SET check_function_bodies = true;
